Make oodeel library agnostic
deel-ai/oodeel pull request #25
Opened 2023-03-28 16:21 UTC by paulnovello

2023-04-17 15:25 UTC, y-prudent reviewed
Great job! Main remarks concern:
- Docstrings to update
- Some unessential code?
- TODO for VIM: use TF/torch operators instead of numpy to speed up computation
- For the tests, the main changes will consist in removing all the `backend` unnecessary arguments and conditions related to this arg

2023-04-17 15:25 UTC, y-prudent commented on oodeel/datasets/ooddataset.py
- [x] `from_directory` is not used anymore. It should be removed from the documentation. => **solved**
- [ ] `get_dataset` is not lib agnostic since `self._data_handler.dict_to_tuple` is not implemented in TorchDataHandler. Moreover, it seems repetitive compared to `prepare`.

2023-04-17 15:25 UTC, y-prudent commented on oodeel/methods/base.py
Deprecated docstring in `OODModel` init.

**suggestion**:
```python
    """Base Class for methods that assign a score to unseen samples.

    Args:
        output_layers_id (List[int]): list of str or int that identify features to output.
            If int, the rank of the layer in the layer list
            If str, the name of the layer. Defaults to [-1],
        input_layers_id (List[int]): = list of str or int that identify the input layer of the
            feature extractor.
            If int, the rank of the layer in the layer list
            If str, the name of the layer. Defaults to None.
    """
```

2023-04-17 15:25 UTC, y-prudent commented on oodeel/methods/base.py
>          """
Depecated args in doctring

2023-04-17 15:25 UTC, y-prudent commented on oodeel/methods/vim.py
**[TODO]**: Make VIM use torch and keras operators instead of numpy to speed up computation!

**=> For a future PR!**

2023-04-17 15:25 UTC, y-prudent commented on oodeel/models/training_funs_tf/keras_models.py
> +        if model_name not in ["toy_convnet"]:
```suggestion
        if model_name != "toy_convnet":
```

2023-04-17 15:25 UTC, y-prudent commented on oodeel/models/training_funs_tf/train_cifar10.py
- [x] `model_name="resnet18"` will not work anymore as this model is not included in keras applications => **solved**
- [x] The `framework` parser argument should be removed => **solved**
- [ ] Is this file really essential to the library?

2023-04-17 15:25 UTC, y-prudent commented on oodeel/models/training_funs_torch/train_cifar10.py
- [x] The `framework` parser argument should be removed => **solved**
- [ ] Is this file really essential to the library?

2023-04-17 15:25 UTC, y-prudent commented on tests/tests_tensorflow/methods/test_tf_dknn.py
> +    ("backend", "input_shape"),
The backend arg is useless since only tf models and datasets are considered.

2023-04-17 15:25 UTC, y-prudent commented on tests/tests_torch/datasets/test_torch_ooddataset.py
> +def test_instanciate_ood_dataset(backend, as_supervised, expected_output):
`as_supervised` argument is not used.

2023-04-17 15:25 UTC, y-prudent commented on tests/tests_torch/datasets/test_torch_ooddataset.py
> +        if backend == "tensorflow"
The backend can not be "tensorflow". The arg `backend` should be removed. Same remark for all the following tests.

2023-04-17 15:25 UTC, y-prudent commented on tests/tests_torch/methods/test_torch_dknn.py
> +    ("backend", "input_shape"),
`backend` arg should be removed! Same remark for all other torch tests in the `methods` directory.

2023-04-19 09:51 UTC, cofri requested changes
Nice PR! Agnostic is all you need
I suggested some changes (see comments). I haven't reviewed tests yet. I will review them this afternoon.

2023-04-19 09:51 UTC, cofri commented on docs/index.md
> +        <img src="https://img.shields.io/badge/Python-3.8, 3.9, 3.10-efefef">
As discussed with Yannick, we can replace this badge to all Python versions above 3.8: https://img.shields.io/badge/Python-3.8+-efefef

2023-04-19 09:51 UTC, cofri commented on oodeel/methods/base.py
> +            self.dh = TFDataHandler()
I found name `dh` not explicit enough. Is `self.data_handler` too long?

2023-04-19 09:51 UTC, cofri commented on oodeel/methods/base.py
> +            raise NotImplementedError(f"not implemented for {type(dataset)}")
Maybe a more precise error message? e.g. `OODModel.score() not implemented for data of type {type(dataset)}`

2023-04-19 09:51 UTC, cofri commented on oodeel/methods/base.py
> +            raise NotImplementedError(f"not implemented for {type(dataset)}")
Same as above, maybe a more explicit error message?

2023-04-19 09:51 UTC, cofri commented on oodeel/methods/base.py
> +        return np.array(oodness, dtype=np.int8)
Why use `np.int8` and not `bool`?

2023-04-19 09:51 UTC, cofri commented on oodeel/models/training_funs_torch/torch_models.py
> +        device (torch.device): On which device to train (CUDA or CPU).
I don't know if it is important for documentation but criterion and device docstrings are after lr_scheduler, whereas it's the opposite in the function's signature.

2023-04-19 09:51 UTC, cofri commented on oodeel/models/torch_feature_extractor.py
>          Args:
Missing docstring for argument `detach`

2023-04-19 09:51 UTC, cofri commented on oodeel/utils/tf_operator.py
> +    def CrossEntropyLoss(reduction: str = "mean"):
`reduction="mean"` is not a supported argument for Keras losses. Maybe do you mean `sum_over_batch_size`? Or even `auto`?

2023-04-19 09:51 UTC, cofri commented on README.md
> +        <img src="https://img.shields.io/badge/Python-3.8, 3.9, 3.10-efefef">
Same as `index.md`, we can instead use https://img.shields.io/badge/Python-3.8+-efefef for more supported Python versions

2023-04-19 12:39 UTC, cofri commented on tests/tests_tensorflow/datasets/test_tf_ooddataset.py
>          ("tensorflow", True, [200, 2, 3, 0.5]),
If only "tensorflow" backend is used in this file, can we remove it from the pytest parametrization?

2023-04-19 12:40 UTC, cofri commented on tests/tests_tensorflow/datasets/test_tf_ooddataset.py
>          ("tensorflow", [1], [2], False, [100, 33, 34, 1, 1]),
Same here

2023-04-19 13:11 UTC, cofri requested changes
Second part of the review for "tests" folder

2023-04-19 13:11 UTC, cofri commented on tests/tests_tensorflow/datasets/test_tf_ooddataset.py
Since there is no more PyTorch in this file, it might be cleaner to remove all "tensorflow" options, like `if backend == "tensorflow"`.

2023-04-19 13:11 UTC, cofri commented on tests/tests_torch/methods/test_torch_mls.py
> +def test_dknn(backend, input_shape):
There are several references to DKNN here that should be replaced with MLS instead: function's name, docstring, OODModel instance's name

2023-04-19 13:11 UTC, cofri commented on tests/tests_torch/methods/test_torch_mls.py
> +    ("backend", "input_shape"),
Here also, `backend` parameter could be removed

2023-04-19 13:11 UTC, cofri commented on tests/tests_torch/methods/test_torch_odin.py
> +def test_dknn(backend, input_shape):
Same here, multiple references to DKNN instead of ODIN

2023-04-19 13:11 UTC, cofri commented on tests/tests_torch/methods/test_torch_vim.py
> +def test_dknn(backend, input_shape):
Same here, multiple references to DKNN instead of VIM

2023-04-19 17:43 UTC, y-prudent commented on oodeel/methods/base.py
> +        return np.array(oodness, dtype=np.int8)
@paulnovello

2023-04-19 17:43 UTC, y-prudent commented on oodeel/methods/base.py
> +            self.dh = TFDataHandler()
@paulnovello

2023-04-20 09:50 UTC, paulnovello commented on oodeel/models/training_funs_torch/train_cifar10.py
Not really, I am deleting it

2023-04-20 09:52 UTC, paulnovello commented on oodeel/methods/vim.py
Agree to leave it for a future PR

2023-04-20 10:13 UTC, paulnovello commented on oodeel/datasets/ooddataset.py
For now I suggest adding a call to `get_dataset` in the `prepare` function to avoid code repetition. This function is used when using `training_func` with is `prepared=False`. I agree that it is discussable, but I leave it for a future PR.
For `self._data_handler.dict_to_tuple`, could you add it to torch_data_handler ?

2023-04-20 13:05 UTC, cofri approved these changes

2023-04-20 13:48 UTC, y-prudent approved these changes
LGTM!

2023-04-20 14:06 UTC, merged