docs: add github actions badges to README
deel-ai/oodeel pull request #33
Opened 2023-05-10 17:20 UTC by y-prudent

**New badges:**
* colored python 3.8+ badge
* github actions badges for pylint, pytest [torch] and pytest [tensorflow]

Check [here](https://github.com/deel-ai/oodeel/tree/docs/fancy_README) to see the result.

2023-05-10 17:23 UTC, paulnovello requested changes
The linter is flake8, be careful. Otherwise perfect

2023-05-10 17:28 UTC, cofri commented on .github/workflows/python-tests-tf.yml
> -name: oodeel tests tensorflow
tox is a generic tool to run multiple checks and tests. It is not specific to unit testing. I think `pytest` or `unit tests` is a better name for this GH action.

2023-05-10 17:28 UTC, cofri commented on .github/workflows/python-tests-torch.yml
> -name: oodeel tests torch
Same here, I suggest a more relevant name, e.g. `pytest`

2023-05-10 17:40 UTC, cofri approved these changes

2023-05-11 12:19 UTC, paulnovello approved these changes
LGTM

2023-05-11 12:19 UTC, merged