Feat/enforce output choice
deel-ai/oodeel pull request #61
Opened 2023-08-24 12:48 UTC by paulnovello

2023-08-24 15:16 UTC, y-prudent requested changes

2023-08-24 15:16 UTC, y-prudent commented on oodeel/methods/base.py
> +                + " or str. To know what to put, have a look at model.summary() "
Maybe recommand the use of str which is safer

2023-08-24 15:16 UTC, y-prudent commented on oodeel/methods/base.py
> +                + "with keras or model.named_module()"
The command for torch is `model.named_modules()`

2023-08-24 15:16 UTC, y-prudent commented on oodeel/methods/dknn.py
> +        output_layers_id List[Union[int, str]]: feature space on which to compute
Forgot the parentheses around the type

2023-08-24 15:16 UTC, y-prudent commented on docs/notebooks/torch/demo_vim_torch.ipynb
`output_layers_id` argument is missing in the call of VIM at cell 8

2023-08-24 15:16 UTC, y-prudent commented on docs/notebooks/torch/demo_dknn_torch.ipynb
`output_layers_id` argument is missing in the call of DKNN at cell 5

2023-08-24 15:16 UTC, y-prudent commented on docs/notebooks/tensorflow/demo_dknn_tf.ipynb
`output_layers_id` argument is missing in the call of DKNN at cell 8

2023-08-24 15:16 UTC, y-prudent commented on oodeel/methods/vim.py
> +            The output_id for the Energy score is set to -1 by default).
remove line about energy scores because a little bit ambiguous

2023-08-24 19:49 UTC, y-prudent commented
LGTM!

2023-08-24 19:49 UTC, y-prudent approved these changes

2023-08-25 12:45 UTC, cofri approved these changes

2023-08-25 13:00 UTC, merged